/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample */

#ifndef _Included_sample
#define _Included_sample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample
 * Method:    shoutout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_shoutout
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
